// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PortManagement.Infrastructure.Persistence;

#nullable disable

namespace PortManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PortManagementDbContext))]
    [Migration("20260821005135_AddIdentityAndRefreshTokens")]
    partial class AddIdentityAndRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("port_management")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", "identity");
                });

            modelBuilder.Entity("PortManagement.Domain.Operations.CargoOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActualEndAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_end_at_utc");

                    b.Property<decimal?>("ActualQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("actual_quantity");

                    b.Property<DateTimeOffset?>("ActualStartAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_start_at_utc");

                    b.Property<string>("CargoType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("cargo_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DangerousCargoClassification")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("dangerous_cargo_classification");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("direction");

                    b.Property<bool>("IsDangerousCargo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dangerous_cargo");

                    b.Property<DateTimeOffset?>("PlannedEndAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_end_at_utc");

                    b.Property<decimal>("PlannedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("planned_quantity");

                    b.Property<DateTimeOffset?>("PlannedStartAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_start_at_utc");

                    b.Property<Guid>("PortCallId")
                        .HasColumnType("uuid")
                        .HasColumnName("port_call_id");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("quantity_unit");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_cargo_operations");

                    b.HasIndex("PortCallId")
                        .HasDatabaseName("ix_cargo_operations_port_call_id");

                    b.ToTable("cargo_operations", "port_management", t =>
                        {
                            t.HasCheckConstraint("ck_cargo_operations_actual_quantity", "actual_quantity IS NULL OR actual_quantity >= 0");

                            t.HasCheckConstraint("ck_cargo_operations_dangerous_classification", "NOT is_dangerous_cargo OR dangerous_cargo_classification IS NOT NULL");

                            t.HasCheckConstraint("ck_cargo_operations_planned_quantity", "planned_quantity >= 0");
                        });
                });

            modelBuilder.Entity("PortManagement.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("registration_number");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_registration_number");

                    b.HasIndex("Type", "IsActive")
                        .HasDatabaseName("ix_organizations_type_is_active");

                    b.ToTable("organizations", "port_management");
                });

            modelBuilder.Entity("PortManagement.Domain.Planning.BerthWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BerthId")
                        .HasColumnType("uuid")
                        .HasColumnName("berth_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<string>("LastChangeReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_change_reason");

                    b.Property<string>("LastChangedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("last_changed_by");

                    b.Property<Guid>("PortCallId")
                        .HasColumnType("uuid")
                        .HasColumnName("port_call_id");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("requested_by");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_berth_windows");

                    b.HasIndex("PortCallId", "Status")
                        .HasDatabaseName("ix_berth_windows_port_call_id_status");

                    b.HasIndex("BerthId", "StartsAtUtc", "EndsAtUtc")
                        .HasDatabaseName("ix_berth_windows_berth_id_starts_at_utc_ends_at_utc");

                    b.ToTable("berth_windows", "port_management", t =>
                        {
                            t.HasCheckConstraint("ck_berth_windows_valid_period", "ends_at_utc > starts_at_utc");
                        });
                });

            modelBuilder.Entity("PortManagement.Domain.Planning.BerthWindowRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BerthWindowId")
                        .HasColumnType("uuid")
                        .HasColumnName("berth_window_id");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at_utc");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("changed_by");

                    b.Property<DateTimeOffset>("NewEndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("new_ends_at_utc");

                    b.Property<DateTimeOffset>("NewStartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("new_starts_at_utc");

                    b.Property<DateTimeOffset>("PreviousEndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("previous_ends_at_utc");

                    b.Property<DateTimeOffset>("PreviousStartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("previous_starts_at_utc");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_berth_window_revisions");

                    b.HasIndex("BerthWindowId", "ChangedAtUtc")
                        .HasDatabaseName("ix_berth_window_revisions_berth_window_id_changed_at_utc");

                    b.ToTable("berth_window_revisions", "port_management");
                });

            modelBuilder.Entity("PortManagement.Domain.PortCalls.PortCall", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_organization_id");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("NextPortUnLocode")
                        .HasMaxLength(5)
                        .HasColumnType("character(5)")
                        .HasColumnName("next_port_un_locode")
                        .IsFixedLength();

                    b.Property<Guid?>("PlannedBerthId")
                        .HasColumnType("uuid")
                        .HasColumnName("planned_berth_id");

                    b.Property<Guid?>("PlannedTerminalId")
                        .HasColumnType("uuid")
                        .HasColumnName("planned_terminal_id");

                    b.Property<Guid>("PortId")
                        .HasColumnType("uuid")
                        .HasColumnName("port_id");

                    b.Property<string>("PreviousPortUnLocode")
                        .HasMaxLength(5)
                        .HasColumnType("character(5)")
                        .HasColumnName("previous_port_un_locode")
                        .IsFixedLength();

                    b.Property<string>("PublicCode")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("public_code");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("purpose");

                    b.Property<Guid?>("ShippingLineOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipping_line_organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("VesselId")
                        .HasColumnType("uuid")
                        .HasColumnName("vessel_id");

                    b.Property<string>("VoyageNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("voyage_number");

                    b.HasKey("Id")
                        .HasName("pk_port_calls");

                    b.HasIndex("AgentOrganizationId")
                        .HasDatabaseName("ix_port_calls_agent_organization_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_port_calls_idempotency_key");

                    b.HasIndex("PlannedTerminalId")
                        .HasDatabaseName("ix_port_calls_planned_terminal_id");

                    b.HasIndex("PublicCode")
                        .IsUnique()
                        .HasDatabaseName("ix_port_calls_public_code");

                    b.HasIndex("ShippingLineOrganizationId")
                        .HasDatabaseName("ix_port_calls_shipping_line_organization_id");

                    b.HasIndex("VesselId")
                        .HasDatabaseName("ix_port_calls_vessel_id");

                    b.HasIndex("PlannedBerthId", "Status")
                        .HasDatabaseName("ix_port_calls_planned_berth_id_status");

                    b.HasIndex("PortId", "Status")
                        .HasDatabaseName("ix_port_calls_port_id_status");

                    b.ToTable("port_calls", "port_management");
                });

            modelBuilder.Entity("PortManagement.Domain.PortCalls.PortCallEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("action");

                    b.Property<string>("Classifier")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("classifier");

                    b.Property<string>("CorrectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("correction_reason");

                    b.Property<DateTimeOffset>("OccursAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurs_at_utc");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phase");

                    b.Property<Guid>("PortCallId")
                        .HasColumnType("uuid")
                        .HasColumnName("port_call_id");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("recorded_by");

                    b.Property<Guid?>("ReplacesEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaces_event_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_port_call_events");

                    b.HasIndex("ReplacesEventId")
                        .HasDatabaseName("ix_port_call_events_replaces_event_id");

                    b.HasIndex("PortCallId", "Phase", "Action", "Classifier", "OccursAtUtc")
                        .HasDatabaseName("ix_port_call_events_port_call_id_phase_action_classifier_occur");

                    b.ToTable("port_call_events", "port_management");
                });

            modelBuilder.Entity("PortManagement.Domain.PortCalls.PortCallStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at_utc");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("changed_by");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("new_status");

                    b.Property<Guid>("PortCallId")
                        .HasColumnType("uuid")
                        .HasColumnName("port_call_id");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("previous_status");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_port_call_status_history");

                    b.HasIndex("PortCallId", "ChangedAtUtc")
                        .HasDatabaseName("ix_port_call_status_history_port_call_id_changed_at_utc");

                    b.ToTable("port_call_status_history", "port_management");
                });

            modelBuilder.Entity("PortManagement.Domain.Ports.Berth", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal>("MaximumBeamMeters")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("maximum_beam_meters");

                    b.Property<decimal>("MaximumDraftMeters")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("maximum_draft_meters");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.PrimitiveCollection<int[]>("SupportedVesselTypes")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("supported_vessel_types");

                    b.Property<Guid>("TerminalId")
                        .HasColumnType("uuid")
                        .HasColumnName("terminal_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<decimal>("UsefulLengthMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("useful_length_meters");

                    b.HasKey("Id")
                        .HasName("pk_berths");

                    b.HasIndex("TerminalId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_berths_terminal_id_code");

                    b.ToTable("berths", "port_management");
                });

            modelBuilder.Entity("PortManagement.Domain.Ports.Port", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("time_zone_id");

                    b.Property<string>("UnLocode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character(5)")
                        .HasColumnName("un_locode")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_ports");

                    b.HasIndex("UnLocode")
                        .IsUnique()
                        .HasDatabaseName("ix_ports_un_locode");

                    b.ToTable("ports", "port_management");
                });

            modelBuilder.Entity("PortManagement.Domain.Ports.Terminal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<Guid>("PortId")
                        .HasColumnType("uuid")
                        .HasColumnName("port_id");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_terminals");

                    b.HasIndex("PortId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_terminals_port_id_code");

                    b.ToTable("terminals", "port_management");
                });

            modelBuilder.Entity("PortManagement.Domain.Vessels.Vessel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BeamMeters")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("beam_meters");

                    b.Property<string>("CallSign")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("call_sign");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FlagCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("flag_code")
                        .IsFixedLength();

                    b.Property<string>("ImoNumber")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("imo_number");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("LengthOverallMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("length_overall_meters");

                    b.Property<decimal>("MaximumDraftMeters")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("maximum_draft_meters");

                    b.Property<string>("Mmsi")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("mmsi");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_vessels");

                    b.HasIndex("ImoNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_vessels_imo_number")
                        .HasFilter("imo_number IS NOT NULL AND is_active");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_vessels_name");

                    b.ToTable("vessels", "port_management");
                });

            modelBuilder.Entity("PortManagement.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", "identity");
                });

            modelBuilder.Entity("PortManagement.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_users_organization_id");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("PortManagement.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "ExpiresAtUtc")
                        .HasDatabaseName("ix_refresh_tokens_user_id_expires_at_utc");

                    b.ToTable("refresh_tokens", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("PortManagement.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PortManagement.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PortManagement.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("PortManagement.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("PortManagement.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PortManagement.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("PortManagement.Domain.Operations.CargoOperation", b =>
                {
                    b.HasOne("PortManagement.Domain.PortCalls.PortCall", "PortCall")
                        .WithMany()
                        .HasForeignKey("PortCallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cargo_operations_port_calls_port_call_id");

                    b.Navigation("PortCall");
                });

            modelBuilder.Entity("PortManagement.Domain.Planning.BerthWindow", b =>
                {
                    b.HasOne("PortManagement.Domain.Ports.Berth", "Berth")
                        .WithMany()
                        .HasForeignKey("BerthId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_berth_windows_berths_berth_id");

                    b.HasOne("PortManagement.Domain.PortCalls.PortCall", "PortCall")
                        .WithMany()
                        .HasForeignKey("PortCallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_berth_windows_port_calls_port_call_id");

                    b.Navigation("Berth");

                    b.Navigation("PortCall");
                });

            modelBuilder.Entity("PortManagement.Domain.Planning.BerthWindowRevision", b =>
                {
                    b.HasOne("PortManagement.Domain.Planning.BerthWindow", "BerthWindow")
                        .WithMany("Revisions")
                        .HasForeignKey("BerthWindowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_berth_window_revisions_berth_windows_berth_window_id");

                    b.Navigation("BerthWindow");
                });

            modelBuilder.Entity("PortManagement.Domain.PortCalls.PortCall", b =>
                {
                    b.HasOne("PortManagement.Domain.Organizations.Organization", "AgentOrganization")
                        .WithMany()
                        .HasForeignKey("AgentOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_port_calls_organizations_agent_organization_id");

                    b.HasOne("PortManagement.Domain.Ports.Berth", "PlannedBerth")
                        .WithMany()
                        .HasForeignKey("PlannedBerthId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_port_calls_berths_planned_berth_id");

                    b.HasOne("PortManagement.Domain.Ports.Terminal", "PlannedTerminal")
                        .WithMany()
                        .HasForeignKey("PlannedTerminalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_port_calls_terminals_planned_terminal_id");

                    b.HasOne("PortManagement.Domain.Ports.Port", "Port")
                        .WithMany()
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_port_calls_ports_port_id");

                    b.HasOne("PortManagement.Domain.Organizations.Organization", "ShippingLineOrganization")
                        .WithMany()
                        .HasForeignKey("ShippingLineOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_port_calls_organizations_shipping_line_organization_id");

                    b.HasOne("PortManagement.Domain.Vessels.Vessel", "Vessel")
                        .WithMany()
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_port_calls_vessels_vessel_id");

                    b.Navigation("AgentOrganization");

                    b.Navigation("PlannedBerth");

                    b.Navigation("PlannedTerminal");

                    b.Navigation("Port");

                    b.Navigation("ShippingLineOrganization");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("PortManagement.Domain.PortCalls.PortCallEvent", b =>
                {
                    b.HasOne("PortManagement.Domain.PortCalls.PortCall", "PortCall")
                        .WithMany()
                        .HasForeignKey("PortCallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_port_call_events_port_calls_port_call_id");

                    b.HasOne("PortManagement.Domain.PortCalls.PortCallEvent", "ReplacesEvent")
                        .WithMany()
                        .HasForeignKey("ReplacesEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_port_call_events_port_call_events_replaces_event_id");

                    b.Navigation("PortCall");

                    b.Navigation("ReplacesEvent");
                });

            modelBuilder.Entity("PortManagement.Domain.PortCalls.PortCallStatusHistory", b =>
                {
                    b.HasOne("PortManagement.Domain.PortCalls.PortCall", "PortCall")
                        .WithMany("StatusHistory")
                        .HasForeignKey("PortCallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_port_call_status_history_port_calls_port_call_id");

                    b.Navigation("PortCall");
                });

            modelBuilder.Entity("PortManagement.Domain.Ports.Berth", b =>
                {
                    b.HasOne("PortManagement.Domain.Ports.Terminal", "Terminal")
                        .WithMany()
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_berths_terminals_terminal_id");

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("PortManagement.Domain.Ports.Terminal", b =>
                {
                    b.HasOne("PortManagement.Domain.Ports.Port", "Port")
                        .WithMany()
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_terminals_ports_port_id");

                    b.Navigation("Port");
                });

            modelBuilder.Entity("PortManagement.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.HasOne("PortManagement.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_organizations_organization_id");
                });

            modelBuilder.Entity("PortManagement.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.HasOne("PortManagement.Infrastructure.Identity.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PortManagement.Domain.Planning.BerthWindow", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("PortManagement.Domain.PortCalls.PortCall", b =>
                {
                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("PortManagement.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
